### ISSUE TITLE
visualize-JS - Authorization Error  401 only in chrome windows

### ISSUE THREAD

**Issue by Beslinda** [TIBCOSoftware/js-visualize#10]
I am using visualiseJS to show jaspersoft reports on the web. In chrome windows I get error 401, In chrome mac it works fine. I can see all the files loading the error appears when requesting:

`https://xxxx.com/jasperserver-pro/rest_v2/resources?folderUri=/folder&recursive=false`

My code: 

```
visualize({
      auth: {
        name: username,
        password: password,
        organization: organization
      }
    }, (v) => {
      v.resourcesSearch({
        folderUri: mobileFolder,
        recursive: false,
        success: (result) => {
           console.log(result)
        }))
```

**Comment by sgwood63** [comment]
Check your Chrome browser console.
Are there exceptions about SameSite cookies?

If so, you are running into the "Chrome 80" issue.
See https://community.jaspersoft.com/wiki/chromium-80-update-february-2020-cross-site-cookie-blocking-jaspersoft

Will leave this issue open to see if this is the issue.

**Comment by Beslinda** [comment]
yes I get a warning on chrome macOS but there the reports run fine and on windows they do not run.

**Comment by sgwood63** [comment]
If the browser console message says the cookies are "blocked" because of SameSite, then visualize won't run. You need to implement a change as outlined in the Jaspersoft community Chrome 80 wiki page.

The Chrome 80 rollout is happening gradually. Looks like you are running different versions of Chrome between Mac and Windows.

**Comment by Beslinda** [comment]
Aha I see. Thank you for your response.
