### ISSUE TITLE
Visualize js is giving error when running in local system

### ISSUE THREAD

**Issue by satishpatro44** [TIBCOSoftware/js-visualize#5]
When running in a local system, it is downloading visualize js file, but not proceeding by giving this error

	visualize.js:54 Uncaught TypeError: Cannot read property '2' of null
		at h (visualize.js:54)
		at _ (visualize.js:54)
		at new N.Rpc (visualize.js:55)
		at Function.l [as rpc] (visualize.js:55)
		at Object.<anonymous> (visualize.js:55)
		at Object.<anonymous> (visualize.js:56)
		at d (visualize.js:56)
		at Object.add [as done] (visualize.js:56)
		at Array.<anonymous> (visualize.js:56)
		at Function.each (visualize.js:56)	

When running the same code in a server like http-server, nginx it is running fine
Checked for 2 jasper server. Faced the same issue. 

For recreation

	<!DOCTYPE html>
	<html>
		<head>
			<script src="https://mobiledemo.jaspersoft.com/jasperserver-pro/client/visualize.js"></script>
			<script>
				visualize({
					auth: {
						name: "joeuser",
						password: "joeuser"
					}
				}, function (v) {
					var dashboard = v.dashboard({
						resource: "/public/Samples/Dashboards/4._New_Dashboard",
						container: "#dashboard",
						error: function(e) {
							alert(e);
						}
					});
				});
			</script>
		</head>
		<body>
			<div id="dashboard">
			  <div><p>Loading...</p></div>
			</div>
		</body>
	</html>

**Comment by satishpatro44** [comment]
It is working in server like http-server & nginx, but not working in directly opening index.html wihtout any server

**Comment by sgwood63** [comment]
Visualize.js only works from pages server from a web server.

**Comment by satishpatro44** [comment]
But, nowhere it is mentioned. Is it?

**Comment by sgwood63** [comment]
This restriction is not explicitly documented.

visualize is only to be deployed embedded in a web application. It is not a standalone JavaScript library.
